services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: prod
    env_file:
      - .env
    command:
      - python
      - src/youtubechatbot/cli.py
    restart: always
    pull_policy: always
